"""add_acesso_permitido_to_usuario

Revision ID: ac083de04a21
Revises: 440def5f382d
Create Date: 2026-02-18 02:12:37.393346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac083de04a21'
down_revision: Union[str, None] = '440def5f382d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('acesso_permitido', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'acesso_permitido')
    # ### end Alembic commands ###
